name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest flake8

      - name: Lint
        run: flake8 src

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -qgit add .github/workflows/ci.yml
git commit -m "ci: improve workflow with separate lint and test steps"
git push
